### ISSUE TITLE
Missing check in IF statement in buildPHPConfig in Plugin.php

### ISSUE THREAD

**Issue by therealgilles** [rollbar/rollbar-php-wordpress#106]
On the following line: https://github.com/rollbar/rollbar-php-wordpress/blob/6c33742d9f752749969ea07de20b2569881f7947/src/Plugin.php#L323

I believe there is a missing check as follows:

```PHP
// if (isset($config[$setting])) {
if (isset($config[$setting]) && 'person_fn' !== $setting) {
```

**Comment by danielmorell** [comment]
There is a lot that needs help in that little block of code. The whole `eval()` thing needs to go away. The way it was initially implemented is a little bit of a footgun. The scary thing is that I'm not entirely sure `person_fn` was meant to be excluded.

**Comment by danielmorell** [comment]
I am going to close this issue for now. We will be addressing the greater problem this line is a part of in an upcoming release.
