### ISSUE TITLE
PHP Fatal error with release 2.7.0

### ISSUE THREAD

**Issue by therealgilles** [rollbar/rollbar-php-wordpress#119]
On the one hand, very happy to see a new release. On the other hand, this:

```PHP
PHP Fatal error:  Uncaught TypeError: Cannot assign string to property Rollbar\Config::$sendMessageTrace of type bool in .../wp-content/plugins/rollbar/php8/vendor/rollbar/rollbar/src/Config.php:692

**Comment by brianr** [comment]
Thank you, @therealgilles . We'll take a look at this.

**Comment by aaronjorbin** [comment]
Hi @therealgilles, thanks for the report and sorry for the issue. I've fixed this and just pushed the update to https://wordpress.org/plugins/rollbar/ (as well as tagged here).
