### ISSUE TITLE
Bug if `$option_pos !== false` is false

### ISSUE THREAD

**Issue by rokob** [rollbar/rollbar-php-wordpress#44]
https://github.com/rollbar/rollbar-php-wordpress/blob/master/src/Settings.php#L326 will throw an undefined variable exception for `$desc` if `$option_pos !== false` evaluates to false.

**Comment by ArturMoczulski** [comment]
This should be resolved by https://github.com/rollbar/rollbar-php-wordpress/pull/43

**Comment by ArturMoczulski** [comment]
Fix has been tagged, released and published in the Wordpress plugin repo.
