### ISSUE TITLE
Submit the plugin to wpackagist for composer-driven projects

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php-wordpress#48]

**Comment by ethanclevenger91** [comment]
My understanding is that this repo and [this plugin](https://wordpress.org/plugins/rollbar/) are the same thing. All WP.org repo-available plugins are automatically available via wpackagist. So this plugin is already available [on wpackagist](https://wpackagist.org/search?q=rollbar&type=any&search=).

**Comment by jessewgibbs** [comment]
@ethanclevenger91 yep looks like this is done.  I'm going to close the issue.
