### ISSUE TITLE
ucwords not compatible with PHP < 5.5.16

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php-wordpress#59]
Issue brought up by a user in the Wordpress plugin directory forum: https://wordpress.org/support/topic/php-warning-ucwords-expects-exactly-1-parameter-2-given/

Hi again

A recent update has meant I am no longer able to use the plugin at all, due to the PHP versions I am running (5.5.9).

PHP Warning: ucwords() expects exactly 1 parameter, 2 given: plugins/rollbar/src/Plugin.php on line 359

Ucwords introduced the delimiter in 5.5.16 and so this generates a warning. Sadly, I have had to disable the plugin.

Regards
M

**Comment by rivkahstandig3636** [comment]
@ArturMoczulski What's the status of this?

**Comment by ArturMoczulski** [comment]
Fixed in `v2.4.3`
