### ISSUE TITLE
PHP Deprecated: Non-static method Rollbar\Wordpress\UI::getIncludedErrnoDescriptions() should not be called statically

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php-wordpress#60]
An issue brought up by a user on the Wordpress plugin directory forum: https://wordpress.org/support/topic/getting-errors-with-plugin-update/

I’m getting loads of the following errors since updating the plugin:

```
PHP Deprecated: Non-static method Rollbar\Wordpress\UI::getIncludedErrnoDescriptions() should not be called statically in /srv/users/serverpilot/apps/myapp/public/wp-content/plugins/rollbar/src/Settings.php on line 162
```

**Comment by jessewgibbs** [comment]
I'm closing this due to old age.  It looks like the support ticket at Wordpress has been closed.

**Comment by ArturMoczulski** [comment]
This has been fixed in the latest releases
