### ISSUE TITLE
Class 'Psr\Log\LogLevel' not found when enabling plugin

### ISSUE THREAD

**Issue by lwcooper** [rollbar/rollbar-php-wordpress#61]
I get the following error every time I try to enable Rollbar:

PHP message: PHP Fatal error:  Class 'Psr\Log\LogLevel' not found in .../web/app/plugins/rollbar/vendor/rollbar/rollbar/src/Defaults.php on line 13

I'm running PHP 7.2 setup using the latest version of trellis (https://roots.io/trellis/docs/remote-server-setup/)

**Comment by ArturMoczulski** [comment]
Did you install the plugin through the Wordpress admin panel or `composer install`?

**Comment by ArturMoczulski** [comment]
Closing the issue until OP gets back to us.
