### ISSUE TITLE
Programmatically configure the plugin

### ISSUE THREAD

**Issue by andreagioco** [rollbar/rollbar-php-wordpress#62]
I'm trying to scrub the information sent to Rollbar, like my user's first_name and last_name for example.

I used the "rollbar_plugin_settings" Wordpress filter as [mentioned in the documentation](https://github.com/rollbar/rollbar-php-wordpress#rollbar_plugin_settings-filter). 
I included it in my function.php file as follow:

```php
function adjust_rollbar_settings($settings)
{
    $settings['scrub_fields'] = [
        'password', 'secret', 'confirm_password', 'password_confirmation',
        'auth_token', 'csrf_token', '_token', 'token', 'bearer', 'Bearer', 'jwt',
        'first_name', 'last_name', 'email', 'mobile', 'phone',
    ];
    return $settings;
}

add_filter('rollbar_plugin_settings', 'adjust_rollbar_settings');
```

It seems that the plugin calls this configuration function on its constructor, but at that point the function.php file hasn't be included yet.

My data are not scrubed and the configuration is ignored.

**Comment by rivkahstandig3636** [comment]
@ArturMoczulski Can you take a look into this?

**Comment by ArturMoczulski** [comment]
Fixed. Will be included in the next release.
