### ISSUE TITLE
Rollbar plugin creating errors and reporting itself (cron)

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-php-wordpress#82]
Issue was brought up on Wordpress plugin page forum: https://wordpress.org/support/topic/rollbar-plugin-creating-errors-and-reporting-itself-cron/

```
Request url /wp-cron.php?doing_wp_cron=1554191111.1389780044555664062500

File /wp-content/plugins/rollbar/src/Settings.php line 103 in session_start

Issue is this line
if( !session_id()) {

Fixed by this change
if( !session_id() && !defined( 'DOING_CRON' )) {
```

**Comment by acobster** [comment]
@ArturMoczulski thanks for addressing this! I found this warning and patched our installation as described above. Just wondering if we can expect this to land in the next release?

**Comment by E-VANCE** [comment]
+1

Still seeing wp_cron errors piling up in our dashboard...

**Comment by acobster** [comment]
The [2.6.1 release](https://downloads.wordpress.org/plugin/rollbar.2.6.1.zip) does not have this change for whatever reason, so this is still a problem for us too.
