### ISSUE TITLE
php 7.4 warning notice kills header output. Wordpress dies.

### ISSUE THREAD

**Issue by andrewmclagan** [rollbar/rollbar-php-wordpress#91]
```bash

Notice: Trying to access array offset on value of type null in /var/www/src/wp-content/plugins/rollbar/src/Plugin.php on line 269

Warning: session_start(): Cannot start session when headers already sent in /var/www/src/wp-content/plugins/rollbar/src/Settings.php on line 103

Warning: Cannot modify header information - headers already sent by (output started at /var/www/src/wp-content/plugins/rollbar/src/Plugin.php:269) in /var/www/src/wordpress/wp-includes/pluggable.php on line 1265

Warning: Cannot modify header information - headers already sent by (output started at /var/www/src/wp-content/plugins/rollbar/src/Plugin.php:269) in /var/www/src/wordpress/wp-includes/pluggable.php on line 1268
```

this should be updated. especially because this is an proprietary error logger. ha.

**Comment by spenserhale** [comment]
@andrewmclagan I have already submitted a patch to resolve your issue back in May of this year. 
see https://github.com/rollbar/rollbar-php-wordpress/pull/84
We are waiting on @ArturMoczulski to submit the update.

You can download the master branch of this project if you want to test the fixes/ use it until they start working on this project again.

**Comment by ArturMoczulski** [comment]
This has been addressed by https://github.com/rollbar/rollbar-php-wordpress/pull/84 and now released in https://github.com/rollbar/rollbar-php-wordpress/releases/tag/v2.6.1
