### ISSUE TITLE
Please, update wordpress plugin info and tests

### ISSUE THREAD

**Issue by sergeybrava** [rollbar/rollbar-php-wordpress#98]
https://wordpress.org/plugins/rollbar/

1) This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

2) Last updated:1 year ago

**Comment by jcanepa** [comment]
Any plans to update the plugin page's info? We're now at 2 years since last updated.

**Comment by ehausen** [comment]
There seem to be this Milestone of v3.0.0 which currently is **Past due by 25 days**

Lets hope the deadline is not moved.

https://github.com/rollbar/rollbar-php-wordpress/milestone/3

**Comment by bishopb** [comment]
@jcanepa and @ehausen working on getting that plugin page updated, but have in the meanwhile confirmed it works on all recent versions.

**Comment by therealgilles** [comment]
Any update on this?

**Comment by danielmorell** [comment]
IT is working on getting me access to the SVN repo, so I can push the latest update to WordPress. I will also be working on making updates to core in the next couple weeks.

**Comment by mikemanger** [comment]
Looks like we got an update, thank you. 🥳 

FYI 10up have developed a great [GitHub action](https://github.com/10up/action-wordpress-plugin-deploy) that takes care of deploying to the WP SVN repo, might be worth considering here.

**Comment by danielmorell** [comment]
@mikemanger You are Welcome! I am a fan of that Github action and I am hoping to add before too long.
